#define IOCTL_DEVICE_TYPE 0x22

#define CTRL_IOCTL CTL_CODE(IOCTL_DEVICE_TYPE, 0x101, 0, 3)
#define INFO_IOCTL CTL_CODE(IOCTL_DEVICE_TYPE, 0x103, 0, 3)
#define INFO_IOCTL_DEPRECATED CTL_CODE(IOCTL_DEVICE_TYPE, 0x100, 0, 3)
